server.port=8080
spring.application.name=api-gateway

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery-based routing (Auto-routes to any service in Eureka)
spring.cloud.gateway.discovery.locator.enabled=true

# Explicit Routes for "Eco-Ride"
# Service 1: User Service
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/users/**

# Service 2: Vehicle Service
spring.cloud.gateway.mvc.routes[1].id=vehicle-service
spring.cloud.gateway.mvc.routes[1].uri=lb://vehicle-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/vehicles/**

# Service 3: Maintenance Service
spring.cloud.gateway.mvc.routes[2].id=maintenance-service
spring.cloud.gateway.mvc.routes[2].uri=lb://maintenance-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/maintenance/**